#!/bin/bash

# Run the experiments and redirect the output to a log file
#消融1：
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.1 --k 3 --with_slow
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.1 --delta 0.1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.1 --delta 0.1 --k 3 --with_slow
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.1 --delta 0.1 --k 3 --with_slow

#消融2：
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 2 --with_slow > ablation_exp/exp2/cifar10_k_2.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 3 --with_slow > ablation_exp/exp2/cifar10_k_3.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 4 --with_slow > ablation_exp/exp2/cifar10_k_4.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 5 --with_slow > ablation_exp/exp2/cifar10_k_5.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 2 --lmbda 0.1 --delta 0.01 --k 2 --with_slow > ablation_exp/exp2/cifar100_k_2.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 2 --lmbda 0.1 --delta 0.01 --k 3 --with_slow > ablation_exp/exp2/cifar100_k_3.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 2 --lmbda 0.1 --delta 0.01 --k 4 --with_slow > ablation_exp/exp2/cifar100_k_4.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 2 --lmbda 0.1 --delta 0.01 --k 5 --with_slow > ablation_exp/exp2/cifar100_k_5.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 2 --with_slow > ablation_exp/exp2/imr_k_2.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 3 --with_slow > ablation_exp/exp2/imr_k_3.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 4 --with_slow > ablation_exp/exp2/imr_k_4.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 --k 5 --with_slow > ablation_exp/exp2/imr_k_5.log 2>&1

#消融3：
#CIFAR100
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.001 --delta 0.001 --gpu-id 0 > ablation_exp/exp3/cifar100_l_0.001_d_0.001.log # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.001 --delta 0.01 > ablation_exp/exp3/cifar100_l_0.001_d_0.01.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.001 --delta 0.1 > ablation_exp/exp3/cifar100_l_0.001_d_0.1.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.01 --delta 0.001 > ablation_exp/exp3/cifar100_l_0.01_d_0.001.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.01 --delta 0.01 > ablation_exp/exp3/cifar100_l_0.01_d_0.01.log 2>&1 #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.01 --delta 0.1 > ablation_exp/exp3/cifar100_l_0.01_d_0.1.log 2>&1 #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.1 --delta 0.001 > ablation_exp/exp3/cifar100_l_0.1_d_0.001.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.1 --delta 0.01 > ablation_exp/exp3/cifar100_l_0.1_d_0.01.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.1 --delta 0.1 > ablation_exp/exp3/cifar100_l_0.1_d_0.1.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 1 --delta 0.001 > ablation_exp/exp3/cifar100_l_1_d_0.001.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 1 --delta 0.01 > ablation_exp/exp3/cifar100_l_1_d_0.01.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 1 --delta 0.1 > ablation_exp/exp3/cifar100_l_1_d_0.1.log 2>&1
#这是不加正则，最后一行
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0 --delta 1 > ablation_exp/exp3/cifar100_l_0_d_1.log 2>&1
#IMR
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.001 --delta 0.001 --gpu-id 1 > ablation_exp/exp3/imr_l_0.001_d_0.001.log # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.001 --delta 0.01 > ablation_exp/exp3/imr_l_0.001_d_0.01.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.001 --delta 0.1 > ablation_exp/exp3/imr_l_0.001_d_0.1.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.01 --delta 0.001 > ablation_exp/exp3/imr_l_0.01_d_0.001.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.01 --delta 0.01 > ablation_exp/exp3/imr_l_0.01_d_0.01.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.01 --delta 0.1 > ablation_exp/exp3/imr_l_0.01_d_0.1.log 2>&1 #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.001 > ablation_exp/exp3/imr_l_0.1_d_0.001.log 2>&1 # #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.01 > ablation_exp/exp3/imr_l_0.1_d_0.01.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.1 > ablation_exp/exp3/imr_l_0.1_d_0.1.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 1 --delta 0.001 > ablation_exp/exp3/imr_l_1_d_0.001.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 1 --delta 0.01 > ablation_exp/exp3/imr_l_1_d_0.01.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 1 --delta 0.1 > ablation_exp/exp3/imr_l_1_d_0.1.log 2>&1
#不加正则
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0 --delta 1 > ablation_exp/exp3/imr_l_0_d_1.log 2>&1

#消融4：
#CIFAR10
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 0.5 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar10_k_0.5.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar10_k_1.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 1.5 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar10_k_1.5.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 500  --csv_log --with_brain_vit --num_classes 10 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar10_k_2.log 2>&1
#CIFAR100
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 0.5 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar100_k_0.5.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar100_k_1.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 1.5 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar100_k_1.5.log 2>&1
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --with_brain_vit --num_classes 100 --num_workers 12 --hidden_dim 768 --kappa 2 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/cifar100_k_2.log 2>&1
#IMR
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 0.5 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/imr_k_0.5.log 2>&1 #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/imr_k_1.log 2>&1 #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 1.5 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/imr_k_1.5.log 2>&1 #
python /home/bqqi/lifelong_research/src/CL_Transformer/utils/main.py --model onlinevt --load_best_args --dataset seq-imagenet-r --buffer_size 600  --csv_log --with_brain_vit --num_classes 200 --num_workers 12 --kappa 2 --lmbda 0.1 --delta 0.01 > ablation_exp/exp4/imr_k_2.log 2>&1 #



